FROM node:alpine

WORKDIR /ShopySavvyAPP

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

RUN apk add --no-cache git

RUN git clone https://github.com/leonardovalde/envtest .

RUN npm install

RUN npm run build

EXPOSE 5173