const test = [
  {
    productId: 2912,
    product: {
      productId: 2912,
      name: 'AGUARDIENTE NÉCTAR CLUB VERDE 375 ML',
      price: '17990',
      photosurl:
        'https://stockimages.tiendasd1.com/stockimages.tiendasd1.com/kobastockimages/IMAGENES/12000358.png',
      unit: 'Unidad',
      subunit: 'mL',
      subqty: '375.0',
      description: '',
      sku: '12000358',
      ean: '7702404005034',
      brand: 'NÉCTAR',
      category: 'bebidas',
      storeName: 'tiendas_d1',
    },
    storeName: 'tiendas_d1',
    quantity: 1,
  },
  {
    productId: 6876,
    product: {
      productId: 6876,
      name: 'Cocoa Corona 100 Gr',
      price: '5810',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/9d1cc30d-1c74-4ba2-a2fd-3b0aaf33ad05.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '7702007031560',
      brand: null,
      category: 'despensa',
      storeName: 'exito',
    },
    storeName: 'exito',
    quantity: 1,
  },
  {
    productId: 4537,
    product: {
      productId: 4537,
      name: 'Pan Perro Comapan 720G En12u',
      price: '9500',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/9a03888e-2683-49d1-8a83-620f7b7f9420.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '7702432005853',
      brand: null,
      category: 'panaderia',
      storeName: 'makro',
    },
    storeName: 'makro',
    quantity: 1,
  },
  {
    productId: 6684,
    product: {
      productId: 6684,
      name: 'Mezcla Sun Tea De Maracuyá X266g Rinde 4.5L ',
      price: '6525',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/1d0da7c5-9d07-42a1-a9d5-de85649c9dd1.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '7702354950576',
      brand: null,
      category: 'despensa',
      storeName: 'jumbo,olimpica,metro',
    },
    storeName: 'jumbo',
    quantity: 1,
  },
  {
    productId: 4483,
    product: {
      productId: 4483,
      name: 'Galletas Crokan Caja Surtida 200 G',
      price: '4990',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/d9ffee14-3bee-4f59-aa29-2b3e5a1a093d.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '1011007027395',
      brand: null,
      category: 'panaderia',
      storeName: 'tiendas_d1',
    },
    storeName: 'tiendas_d1',
    quantity: 1,
  },
  {
    productId: 6483,
    product: {
      productId: 6483,
      name: 'Mezcla Te Neg Premium Cafe Hindu 32 Gr',
      price: '11990',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/86e48f87-da08-4ad1-9f64-a88ed4c03111.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '7702746014060',
      brand: null,
      category: 'despensa',
      storeName: 'exito,jumbo,carulla,olimpica,metro,makro',
    },
    storeName: 'carulla',
    quantity: 1,
  },
  {
    productId: 6483,
    product: {
      productId: 6483,
      name: 'Mezcla Te Neg Premium Cafe Hindu 32 Gr',
      price: '11990',
      photosurl:
        'https://imagescomparalo.blob.core.windows.net/imagenes-productos/86e48f87-da08-4ad1-9f64-a88ed4c03111.jpg',
      unit: null,
      subunit: null,
      subqty: null,
      description: null,
      sku: null,
      ean: '7702746014060',
      brand: null,
      category: 'despensa',
      storeName: 'exito,jumbo,carulla,olimpica,metro,makro',
    },
    storeName: 'olimpica',
    quantity: 1,
  },
];

const productsByStore = Object.groupBy(test, (product) => product.storeName);
console.log(productsByStore);
